# Generated by Django 5.1.7 on 2025-03-10 17:47

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='default/profile.jpeg', upload_to=apps.core.services.get_path_upload_image_artist, validators=[apps.core.services.validate_image_size], verbose_name='image'),
        ),
    ]
