# Generated by Django 4.2.20 on 2025-05-05 15:27

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_remove_track_license_alter_track_album_and_more'),
        ('artists', '0002_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='default/profile.webp', upload_to=apps.core.services.get_path_upload_image_artist, validators=[apps.core.services.validate_image_size], verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
