# Generated by Django 4.2.20 on 2025-05-05 15:27

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, default='default/album.png', upload_to=apps.core.services.get_path_upload_image_album, validators=[apps.core.services.validate_image_size], verbose_name='image'),
        ),
    ]
