# Generated by Django 4.2.20 on 2025-05-05 15:27

import apps.core.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_image'),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='license',
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, default='default/album.png', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='albums.album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, default='default/album.png', upload_to=apps.core.services.get_path_upload_image_track, validators=[apps.core.services.validate_image_size], verbose_name='image'),
        ),
    ]
