# Generated by Django 5.1.7 on 2025-03-10 17:47

import apps.core.services
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_date_joined_user_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='UA', max_length=2, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.core.services.get_path_upload_image_user, validators=[apps.core.services.validate_image_size], verbose_name='image'),
        ),
    ]
