# Generated by Django 5.1.7 on 2025-03-08 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='viewer IP')),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_plays', to='playlists.playlist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist Play',
                'verbose_name_plural': 'Playlist Plays',
                'unique_together': {('user', 'playlist', 'viewer_ip')},
            },
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='score')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='audio.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Similarity',
                'verbose_name_plural': 'Similarities',
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.CreateModel(
            name='TrackPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='viewer IP')),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='audio.track')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Track Play',
                'verbose_name_plural': 'Track Plays',
                'unique_together': {('user', 'track', 'viewer_ip')},
            },
        ),
    ]
